### ISSUE TITLE
Adding ng bootstrap for twitter bootstrap cause failure to build nom start

### ISSUE THREAD

**Issue by PSPanesar** [designcourse/angular-seo#1]
Hi,
Thanks for the tutorial. I've setup the same steps for my angular 4 app which works fine but when i add ng-bootstrap with npm install --save @ng-bootstrap/ng-bootstrap then import it to my module with import {NgbModule} from '@ng-bootstrap/ng-bootstrap and imports: [NgbModule.forRoot()] then the whole app fails to compile with npm start or production build. Could you help and let me know what is going wrong?
Thanks

**Comment by nomanHasan** [comment]
I'm facing the same issue here, importing Material Module produces this error -
```
dist\ngfactory\node_modules\@angular\material\typings\index.ngfactory.ts:9
import * as import0 from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import
at createScript (vm.js:53:10)
at Object.runInThisContext (vm.js:95:10)
at Module._compile (module.js:543:28)
at Module._extensions..js (module.js:580:10)
```

Or After importing the NgxBootstrap This error - 
```node_modules\ngx-bootstrap\dropdown\bs-dropdown.module.js:1
(function (exports, require, module, __filename, __dirname) { import { NgModule } from '@angular/core';
                                                          ^^^^^^
SyntaxError: Unexpected token import
at createScript (vm.js:53:10)
at Object.runInThisContext (vm.js:95:10)
at Module._compile (module.js:543:28)
at Object.Module._extensions..js (module.js:580:10)
```

I'm guessing this issue is for all imports of third party modules.

**Comment by deepakzoto** [comment]
I am also getting the same error. Any solution to this problem?

**Comment by Shyam-Chen** [comment]
```bash
.../dist/ngfactory/node_modules/@angular/material/typings/index.ngfactory.ts:9
import * as i0 from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import
```

**Comment by wnabil** [comment]
the problem is the js es5 as i see on stackoverflow.
so we need to change the target to es6 then use the babel js to convert it because the express engine only supports es5
so the question is how to use babel with angular cli !?

**Comment by wnabil** [comment]
maybe this will help someone : 
https://github.com/designcourse/angular-seo/issues/3#issuecomment-313346304
i tested it with ng-bootstrap and it works

**Comment by ali-habibzadeh** [comment]
Same problem here
