### ISSUE TITLE
issue if i npm run start 

### ISSUE THREAD

**Issue by rohitazad** [designcourse/angular-seo#20]
![image](https://user-images.githubusercontent.com/6701640/34561287-4ecd3154-f16f-11e7-8558-07fba8767495.png)

**Comment by akilmakda** [comment]
run :npm install enhanced-resolve@3.3.0

in your pakage.json file.. in script tag replace this "ng build --prod" with "ng build --env=prod". It will reolve the problem. 

Thankyou

**Comment by rohitazad** [comment]
@akilmakda Thanks it's working example 👍
